
USE ROLE ACCOUNTADMIN;
CREATE DATABASE ECO_SYSTEM_DB_1;

CREATE OR REPLACE SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA WITH MANAGED ACCESS;

CREATE ROLE S_FULL;
CREATE ROLE S_WRITE;
CREATE ROLE S_READ;

GRANT 
    MODIFY, MONITOR, USAGE, CREATE TABLE, CREATE EXTERNAL TABLE, CREATE VIEW, CREATE MATERIALIZED VIEW,
    CREATE MASKING POLICY, CREATE SEQUENCE, CREATE FUNCTION, CREATE PROCEDURE, CREATE FILE FORMAT,
    CREATE STAGE, CREATE PIPE, CREATE STREAM, CREATE TASK
    ON SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA 
    TO ROLE S_FULL;


GRANT 
    SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES 
    ON ALL TABLES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA 
    TO ROLE S_FULL;


GRANT 
    SELECT
    ON ALL EXTERNAL TABLES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_FULL;

GRANT 
    SELECT
    ON ALL VIEWS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_FULL;

GRANT 
    SELECT
    ON ALL MATERIALIZED VIEWS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_FULL;

GRANT 
    SELECT
    ON ALL STREAMS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_FULL;

GRANT 
    USAGE
    ON ALL FUNCTIONS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_FULL;

GRANT 
    USAGE
    ON ALL PROCEDURES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_FULL;

GRANT 
    USAGE
    ON ALL FILE FORMATS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_FULL;


// WRITE??
GRANT 
    USAGE, READ, WRITE
    ON ALL STAGES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_FULL;

GRANT 
    USAGE
    ON ALL SEQUENCES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_FULL;


GRANT
    MODIFY, MONITOR, USAGE, CREATE TABLE, CREATE EXTERNAL TABLE, CREATE VIEW, 
    CREATE MATERIALIZED VIEW, CREATE SEQUENCE, CREATE FUNCTION, 
    CREATE PROCEDURE, CREATE FILE FORMAT
    ON SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON ALL TABLES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    SELECT
    ON ALL EXTERNAL TABLES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    SELECT
    ON ALL VIEWS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    SELECT
    ON ALL MATERIALIZED VIEWS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    SELECT
    ON ALL STREAMS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    USAGE
    ON ALL FUNCTIONS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    USAGE
    ON ALL PROCEDURES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    USAGE
    ON ALL FILE FORMATS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    USAGE, READ, WRITE
    ON ALL STAGES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    USAGE
    ON ALL SEQUENCES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_WRITE;

GRANT
    USAGE
    ON SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

GRANT
    SELECT, REFERENCES
    ON ALL TABLES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

GRANT
    SELECT
    ON ALL EXTERNAL TABLES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

GRANT
    SELECT
    ON ALL VIEWS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

GRANT
    SELECT
    ON ALL MATERIALIZED VIEWS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

// powinno być stream select a nie usage w s_read
GRANT
    SELECT
    ON ALL STREAMS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

GRANT
    USAGE
    ON ALL FUNCTIONS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

GRANT
    USAGE
    ON ALL PROCEDURES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

// usage read write do file format??
GRANT
    USAGE
    ON ALL FILE FORMATS IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

GRANT
    USAGE
    ON ALL STAGES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;

GRANT
    USAGE
    ON ALL SEQUENCES IN SCHEMA ECO_SYSTEM_DB_1.MANAGED_SCHEMA
    TO ROLE S_READ;


 CREATE ROLE D_FULL;
 CREATE ROLE D_USAGE;

 GRANT
    USAGE
    ON DATABASE ECO_SYSTEM_DB_1
    TO ROLE D_USAGE;

GRANT
    USAGE, MODIFY, MONITOR, CREATE SCHEMA
    ON DATABASE ECO_SYSTEM_DB_1
    TO ROLE D_FULL;

GRANT ROLE S_FULL TO ROLE D_FULL;

CREATE ROLE LOCAL_ADMIN_ROLE;

GRANT ROLE D_FULL TO ROLE LOCAL_ADMIN_ROLE;

GRANT 
    CREATE ROLE, CREATE USER on account TO ROLE LOCAL_ADMIN_ROLE WITH GRANT OPTION;

CREATE USER admin_user PASSWORD = '123' DEFAULT_ROLE = LOCAL_ADMIN_ROLE;


USE ROLE ACCOUNTADMIN;

GRANT OWNERSHIP ON ROLE D_USAGE TO LOCAL_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE S_WRITE TO LOCAL_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE S_READ TO LOCAL_ADMIN_ROLE REVOKE CURRENT GRANTS;

GRANT OWNERSHIP ON ROLE D_FULL TO LOCAL_ADMIN_ROLE REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON ROLE S_FULL TO LOCAL_ADMIN_ROLE REVOKE CURRENT GRANTS;

GRANT ROLE LOCAL_ADMIN_ROLE TO USER admin_user;

GRANT ROLE LOCAL_ADMIN_ROLE TO ROLE SYSADMIN;

